services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: smartstock@@2024
      MYSQL_DATABASE: smartstock
      MYSQL_USER: sa
      MYSQL_PASSWORD: smartstock@@2024
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
