name: Sync with Original Repository

on:
  schedule:
    # Executa o workflow a cada hora (ajuste conforme necessário)
    - cron: '* * * * *' # A cada 1 min

jobs:
  sync:
    # Usa o runner padrão do GitHub (não precisa configurar nada localmente)
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório clonado
      - name: Checkout Cloned Repository
        uses: actions/checkout@v2

      # Sincroniza as alterações da branch 'main' do upstream para o repositório clonado
      - name: Merge Upstream Changes
        run: |
          git checkout main
          git fetch upstream main
          git merge upstream/main
          git push origin main
