name: Sync with Original Repository

on:
  schedule:
    - cron: '* * * * *' # A cada 1 min

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório clonado
      - name: Checkout Cloned Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Garante que todo o histórico seja baixado

      # Adiciona o repositório upstream
      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/ICEI-PUC-Minas-PMV-ADS/PMV-ADS-2024-2-E2-Proj-Smart-Stock.git

      # Sincroniza as alterações da branch 'main' do upstream para o repositório clonado
      - name: Merge Upstream Changes
        run: |
          git checkout main
          git fetch upstream main
          git merge upstream/main
          git push origin main
